import { type Types } from 'models/models';

export const gen1List: string[] = [
	'bulbasaur',
	'venusaur',
	'charizard',
	'butterfree',
	'beedrill',
	'arbok',
	'sandslash',
	'nidoqueen',
	'nidoking',
	'vileplume',
	'parasect',
	'venomoth',
	'alakazam',
	'victreebel',
	'tentacruel',
	'golem',
	'muk',
	'cloyster',
	'gengar',
	'rhyhorn',
	'rhydon',
	'starmie',
	'scyther',
	'pinsir',
	'gyarados',
	'lapras',
	'porygon',
	'omastar',
	'kabutops',
	'aerodactyl',
	'articuno',
	'zapdos',
	'moltres',
	'mewtwo',
	'mew',
];

export const gen2List: string[] = [
	'meganium',
	'ariados',
	'ampharos',
	'slowking',
	'forretress',
	'gligar',
	'steelix',
	'scizor',
	'shuckle',
	'heracross',
	'mantine',
	'skarmory',
	'kingdra',
	'donphan',
	'porygon2',
	'raikou',
	'entei',
	'suicune',
	'tyranitar',
	'lugia',
	'ho-oh',
	'celebi',
];

export const gen3List: string[] = [
	'sceptile',
	'swampert',
	'beautifly',
	'dustox',
	'gardevoir',
	'masquerain',
	'breloom',
	'ninjask',
	'shedinja',
	'exploud',
	'hariyama',
	'sableye',
	'mawile',
	'aggron',
	'sharpedo',
	'wailord',
	'camerupt',
	'torkoal',
	'flygon',
	'altaria',
	'seviper',
	'lunatone',
	'solrock',
	'crawdaunt',
	'claydol',
	'cradily',
	'armaldo',
	'milotic',
	'banette',
	'dusclops',
	'absol',
	'glalie',
	'walrein',
	'relicanth',
	'salamence',
	'metagross',
	'regirock',
	'regice',
	'registeel',
	'latias',
	'latios',
	'kyogre',
	'groudon',
	'rayquaza',
	'jirachi',
	'deoxys-normal',
	'deoxys-attack',
	'deoxys-defense',
	'deoxys-speed',
];

export const gen4List: string[] = [
	'torterra',
	'empoleon',
	'staraptor',
	'rampardos',
	'bastiodon',
	'mothim',
	'gastrodon',
	'drifblim',
	'mismagius',
	'bronzong',
	'spiritomb',
	'garchomp',
	'lucario',
	'hippowdon',
	'drapion',
	'abomasnow',
	'magnezone',
	'tangrowth',
	'electivire',
	'magmortar',
	'togekiss',
	'yanmega',
	'gliscor',
	'mamoswine',
	'porygon-z',
	'dusknoir',
	'uxie',
	'azelf',
	'dialga',
	'palkia',
	'heatran',
	'regigigas',
	'giratina-altered',
	'cresselia',
	'manaphy',
	'darkrai',
	'shaymin-land',
	'arceus',
];

export const gen5List: string[] = [
	'victini',
	'serperior',
	'samurott',
	'gigalith',
	'scolipede',
	'krookodile',
	'darmanitan-standard',
	'crustle',
	'sigilyph',
	'carracosta',
	'archeops',
	'escavalier',
	'galvantula',
	'ferrothorn',
	'klinklang',
	'eelektross',
	'beheeyem',
	'chandelure',
	'haxorus',
	'cryogonal',
	'mienshao',
	'druddigon',
	'golurk',
	'mandibuzz',
	'heatmor',
	'durant',
	'hydreigon',
	'volcarona',
	'tornadus-therian',
	'thundurus-incarnate',
	'thundurus-therian',
	'reshiram',
	'zekrom',
	'landorus-incarnate',
	'landorus-therian',
	'kyurem',
	'genesect',
];

export const gen6List: string[] = [
	'delphox',
	'greninja',
	'vivillon',
	'florges',
	'aegislash-shield',
	'aegislash-blade',
	'malamar',
	'barbaracle',
	'dragalge',
	'clawitzer',
	'heliolisk',
	'tyrantrum',
	'aurorus',
	'goodra',
	'trevenant',
	'gourgeist-average',
	'noivern',
	'xerneas',
	'yveltal',
	'zygarde-50',
	'zygarde-complete',
	'diancie',
	'hoopa',
	'volcanion',
];

export const gen7List: string[] = [
	'vikavolt',
	'crabominable',
	'ribombee',
	'toxapex',
	'araquanid',
	'shiinotic',
	'salazzle',
	'comfey',
	'golisopod',
	'turtonator',
	'dhelmise',
	'kommo-o',
	'tapu-koko',
	'tapu-lele',
	'tapu-bulu',
	'tapu-fini',
	'lunala',
	'nihilego',
	'buzzwole',
	'pheromosa',
	'xurkitree',
	'celesteela',
	'kartana',
	'guzzlord',
	'necrozma',
	'magearna',
	'marshadow',
	'naganadel',
	'stakataka',
	'blacephalon',
	'zeraora',
	'melmetal',
];

export const gen8List: string[] = [
	'rillaboom',
	'cinderace',
	'inteleon',
	'corviknight',
	'orbeetle',
	'eldegoss',
	'drednaw',
	'coalossal',
	'flapple',
	'appletun',
	'sandaconda',
	'barraskewda',
	// 'toxtricity',
	// 'centiskorch',
	// 'grapploct',
	// 'cursola',
	// 'runerigus',
	// 'falinks',
	// 'frosmoth',
	// 'stonjourner',
	// 'dracozolt',
	// 'arctozolt',
	// 'dracovish',
	// 'arctovish',
	// 'duraludon',
	// 'dragapult',
	// 'zacian',
	// 'zacian-crowned',
	// 'eternatus',
	// 'urshifu',
	// 'urshifu-rapid-strike',
	// 'regieleki',
	// 'spectrier',
	// 'calyrex-shadow',
	// 'ursaluna',
	// 'sneasler',
];

export const gen9List: string[] = [
	'meowscarada',
	'skeledirge',
	'spidops',
	'lokix',
	'garganacl',
	'ceruledge',
	'bellibolt',
	'kilowattrel',
	'brambleghast',
	'klawf',
	'scovillain',
	'rabsca',
	'tinkaton',
	// 'palafin',
	// 'revavroom',
	// 'glimmora',
	// 'cetitan',
	// 'veluza',
	// 'dondozo',
	// 'annihilape',
	// 'clodsire',
	// 'dudunsparce',
	// 'great tusk',
	// 'flutter mane',
	// 'slither wing',
	// 'sandy shocks',
	// 'iron hands',
	// 'iron jugulis',
	// 'iron moth',
	// 'iron thorns',
	// 'baxcalibur',
	// 'gholdengo',
	// 'wo-chien',
	// 'chien-pao',
	// 'ting-lu',
	// 'chi-yu',
	// 'roaring moon',
	// 'koraidon',
	// 'miraidon',
	// 'walking wake',
	// 'archaludon',
	// 'hydrapple',
	// 'gouging fire',
	// 'raging bolt',
	// 'iron boulder',
	// 'terapagos',
	// 'pecharunt',
];

export const megasList: string[] = [
	'venusaur-mega',
	'charizard-mega-x',
	'charizard-mega-y',
	'blastoise-mega',
	'alakazam-mega',
	'gengar-mega',
	'kangaskhan-mega',
	'pinsir-mega',
	'gyarados-mega',
	'aerodactyl-mega',
	'mewtwo-mega-x',
	'mewtwo-mega-y',
	'ampharos-mega',
	'scizor-mega',
	'heracross-mega',
	'tyranitar-mega',
	'gardevoir-mega',
	'mawile-mega',
	'aggron-mega',
	'banette-mega',
	'absol-mega',
	'latias-mega',
	'latios-mega',
	'garchomp-mega',
	'lucario-mega',
	'abomasnow-mega',
	'beedrill-mega',
	'steelix-mega',
	'sceptile-mega',
	'sableye-mega',
	'sharpedo-mega',
	'camerupt-mega',
	'altaria-mega',
	'glalie-mega',
	'salamence-mega',
	'metagross-mega',
	'rayquaza-mega',
	'diancie-mega',
];

export const fossilsList: string[] = [
	'omastar',
	'kabutops',
	'aerodactyl',
	'cradily',
	'armaldo',
	'rampardos',
	'bastiodon',
	'carracosta',
	'archeops',
	'tyrantrum',
	'aurorus',
	'dracozolt',
	'arctozolt',
	'dracovish',
	'arctovish',
];

export const legendariesList: string[] = [
	'eternatus',
];

export const regionalsList: string[] = [
	'sandslash-alola',
	'golem-alola',
	'muk-alola',
	'articuno-galar',
	'zapdos-galar',
	'moltres-galar',
	'slowking-galar',
	'samurott-hisui',
	'darmanitan-galar-standard',
	'goodra-hisui',
];

export const pokemonLists = {
	gen1List,
	gen2List,
	gen3List,
	gen4List,
	gen5List,
	gen6List,
	gen7List,
	gen8List,
	gen9List,
	megasList,
	fossilsList,
	legendariesList,
	regionalsList
};

export const typeColors: Types = {
	normal: '#A8A878',
	fire: '#F08030',
	fighting: '#C03028',
	water: '#6890F0',
	flying: '#A890F0',
	grass: '#78C850',
	poison: '#A040A0',
	electric: '#F8D030',
	ground: '#E0C068',
	psychic: '#F85888',
	rock: '#B8A038',
	ice: '#98D8D8',
	bug: '#A8B820',
	dragon: '#7038F8',
	ghost: '#705898',
	dark: '#705848',
	steel: '#B8B8D0',
	fairy: '#EE99AC',
};

export const pages = [
	'Gen 1',
	'Gen 2',
	'Gen 3',
	'Gen 4',
	'Gen 5',
	'Gen 6',
	'Gen 7',
	'Gen 8',
	'Gen 9',
	'Megas',
	'Fossils',
	'Legendaries',
	'Regionals'
];
